# Getting start Numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([1,2,3,234333], np.int8)

np.int8 | np.int16 | np.int32 | np.int64

In [3]:
myarr

array([ 1,  2,  3, 93], dtype=int8)

In [4]:
myarr2d = np.array([[1,2,3,234333]], np.int32)

In [5]:
myarr2d

array([[     1,      2,      3, 234333]])

In [6]:
myarr2d[0, 1]

2

In [7]:
myarr2d.shape

(1, 4)

In [ ]:
myarr2d[0, 3]

In [ ]:
myarr2d[0, 0] = 45

In [ ]:
myarr2d

# ***Array creation: Conversion from other Python structure***

In [ ]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
listarray

In [ ]:
listarray.size

In [ ]:
listarray.shape

In [ ]:
listarray.dtype

In [ ]:
zeros = np.zeros((2,5))

In [ ]:
zeros

In [ ]:
zeros.dtype

In [ ]:
rng = np.arange(15)

***np.arange give array not list***

In [ ]:
rng

In [ ]:
rng.dtype

In [ ]:
lspace = np.linspace(1,5,12)

In [ ]:
lspace

In [ ]:
lspace2 = np.linspace(1,50,5)

In [ ]:
lspace2

In [ ]:
emp = np.empty((4,3))

***Gives new so called empty array of size mentioned with random elements***

In [ ]:
emp

In [ ]:
emp_like = np.empty_like(lspace2)

***Gives new so called empty array of size of previously created array with random elements***

In [ ]:
emp_like

In [ ]:
ide = np.identity(6)

***Gives 6x6 identity matrix***

In [ ]:
ide

In [ ]:
ide.shape

In [ ]:
arr1 = np.arange(99)

In [ ]:
arr1

In [ ]:
arr1.reshape(3,33)

In [ ]:
arr1

In [ ]:
arr1 = arr1.reshape(3,33)

In [ ]:
arr1

In [ ]:
arr1.ravel()

In [ ]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [ ]:
x

In [ ]:
ar = np.array(x)

In [ ]:
ar

In [ ]:
ar.sum(axis=0)

In [ ]:
ar.sum(axis=1)

In [ ]:
ar.T

In [ ]:
for i in ar:
    print(i)

In [ ]:
ar[1]

In [ ]:
print(ar[1])

In [ ]:
ar.flat

In [ ]:
for i in ar.flat:
    print(i)

In [ ]:
for i in ar.flat:
    print(i,end=' ')

In [ ]:
ar.ndim  #  number of dimensions

In [ ]:
ar.size

In [ ]:
ar.nbytes

In [ ]:
one = np.array([1,2,3,345,6])

In [ ]:
one.argmax() #  gives index of max element

In [ ]:
one.argmin() #  gives index of min element

In [ ]:
one = np.array([1,6,3,345,2])

In [ ]:
one

In [ ]:
one

In [ ]:
one.argsort() #  gives the indexes to sort the array

In [ ]:
one.sort() # sort the array and rewrite it

In [ ]:
one

In [ ]:
one

In [ ]:
ar

In [ ]:
ar.argmin()

In [ ]:
ar.argmax(axis=0)

In [ ]:
ar.argmax(axis=1)

In [ ]:
ar.argmax()

In [ ]:
ar.argsort()

In [ ]:
ar

In [ ]:
ar2 = np.array([[1, 2, 3],
       [4, 8, 6],
       [7, 3, 0]])

In [ ]:
ar+ar2

In [ ]:
ar*ar2

In [ ]:
np.sqrt(ar)

In [ ]:
np.square(ar)

In [ ]:
ar

In [ ]:
np.where(ar>5)

***Axis no. and Element index are different***

In [ ]:
np.where(ar<5)

In [ ]:
np.count_nonzero(ar)

In [ ]:
np.nonzero(ar)

In [ ]:
import sys

In [ ]:
py_ar = [1,32,2,3]

In [ ]:
np_ar = np.array(py_ar)

In [ ]:
sys.getsizeof(1)*len(py_ar)

In [ ]:
np_ar.itemsize*np_ar.size

In [ ]:
np_ar

In [ ]:
np_ar.tolist()

In [73]:
ar2 = np.array([[1, 2, 3],
       [4, 8, 6],
       [7, 3, 0]])

In [74]:
ar+ar2

array([[ 2,  4,  6],
       [ 8, 13, 12],
       [14,  4,  0]])

In [75]:
ar*ar2

array([[ 1,  4,  9],
       [16, 40, 36],
       [49,  3,  0]])

In [76]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [77]:
np.square(ar)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])

In [78]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [79]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

***Axis no. and Element index are different***

In [80]:
np.where(ar<5)

(array([0, 0, 0, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [81]:
np.count_nonzero(ar)

8

In [82]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [83]:
import sys

In [84]:
py_ar = [1,32,2,3]

In [89]:
np_ar = np.array(py_ar)

In [86]:
sys.getsizeof(1)*len(py_ar)

112

In [87]:
np_ar.itemsize*np_ar.size

16

In [91]:
np_ar

array([ 1, 32,  2,  3])

In [92]:
np_ar.tolist()

[1, 32, 2, 3]